AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
ConditionalAssignment:
  Enabled: false
